service: default
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

endpoints_api_service:
  name: default-dot-PROJECT_ID.appspot.com
  config_id: CONFIG_ID

env_variables:
    # The app will look for the model file at: gs://MODEL_BUCKET/MODEL_FILENAME
    MODEL_BUCKET: BUCKET_NAME
    MODEL_FILENAME: lr.pkl
